### ISSUE TITLE
Won't install on dev version of Brackets

### ISSUE THREAD

**Issue by jmo7** [salt42/blueprint#1]
Here's the error message (with my user name scrubbed):

[Extension] failed to load /Users/USER_NAME/Library/Application Support/Brackets/extensions/user/blueprint.outliner Error: Script error for: outliner
http://requirejs.org/docs/errors.html#scripterror ExtensionLoader.js:214
errback ExtensionLoader.js:214
(anonymous function) jquery-2.1.0.min.js:2
j jquery-2.1.0.min.js:2
k.fireWith jquery-2.1.0.min.js:2
e.(anonymous function) jquery-2.1.0.min.js:2
j jquery-2.1.0.min.js:2
k.fireWith jquery-2.1.0.min.js:2
e.(anonymous function) jquery-2.1.0.min.js:2
(anonymous function) require.js:129
(anonymous function) require.js:1155
each require.js:57
Module.emit require.js:1154
(anonymous function) require.js:754
(anonymous function) require.js:129
(anonymous function) require.js:129
(anonymous function) require.js:1155
each require.js:57
Module.emit require.js:1154
(anonymous function) require.js:530
each require.js:57
onError require.js:523
context.onScriptError require.js:1666

**Comment by salt42** [comment]
some files where missing :/  thx for the hint.
