### ISSUE TITLE
Outline, not correctly displaying changing the sidebar width.

### ISSUE THREAD

**Issue by DDaems** [salt42/blueprint#13]
Hi, first off all i think its a great plugin.
And i love how easely i can jump to parts to code parts.
But i noticed that the outline moves too when you change the width of your sidebar.
I expect this is a know problem, but i'm still reporting it.
Because it would be awesome if it could get fixed.
Now i allways need to restart brackets or resize to origenal size.

normal:
![normal](https://cloud.githubusercontent.com/assets/7575436/5124033/b57710e6-70b2-11e4-897f-8ed90652e7eb.jpg)  

after i moved the sidebar:
![sidebarmoved](https://cloud.githubusercontent.com/assets/7575436/5124035/b8c83ea0-70b2-11e4-8433-40a48fad2565.jpg)

**Comment by salt42** [comment]
is this the last version 0.9.0?

**Comment by DDaems** [comment]
Yes, i also updated to 0.9.1 today.
And the problem still exist. It happens when changing the width of the left sidebar.

Sorry for my late response
