### ISSUE TITLE
minimap empty

### ISSUE THREAD

**Issue by brainstormtrooper** [salt42/blueprint#14]
After updating to 0.9.1 the minimap is now empty :-(

**Comment by salt42** [comment]
can you pls post me a list with all extensions that you're running.

thx

**Comment by brainstormtrooper** [comment]
wordhint, integrated-development, php-syntax-hint, classcompletion, bookmarks, smarty, todo, quickdocsphp, spellcheck, snippets...

sorry for the delay...
hope this helps.

**Comment by brainstormtrooper** [comment]
it seems that the snippets extension causes the problem... I'll keep testing, but for now, if I disable snippets, then the minimap comes back...
