### ISSUE TITLE
Does Not Show Comments in Minimap

### ISSUE THREAD

**Issue by charlwillia6** [salt42/blueprint#19]
The minimap view does not show comments.  The only reason that this is a concern is that I am working with files that have a lot of comments at the end of the files and I would like to scroll quickly to those sections of the file too.  It does leave dark space at the end of the file, but I would like to see those comments in the minimap for better prediction of where they are in the file.

Maybe text-wrapping too in the minimap as a feature request.  I know that really is petty, but I believe it would make the view more useful.

**Comment by salt42** [comment]
i think i allready fixed it. i will update next days.

what you mean with text-wrapping in the minimap?

**Comment by charlwillia6** [comment]
Nevermind on the text-wrapping request.  I realize now that that would not be necessary or convenient.  Thanks for the great add-on!
