### ISSUE TITLE
Can't close settings dialog

### ISSUE THREAD

**Issue by antonbabkin** [salt42/blueprint#2]
When I open "Settings" dialog of this extension, I can't find a way to close it. It blocks the whole application and I have to terminate it. Besides, settings window is in black letters on dark background, very hard to read.

**Comment by jmo7** [comment]
Awesome!   Thank you.  =)

Jeff Moyes

UX - Web Developer
jeffmoyes@familysearch.orgmailto:jeffmoyes@familysearch.org

On Oct 28, 2014, at 12:32 PM, Anton Babkin <notifications@github.com<mailto:notifications@github.com>> wrote:

When I open "Settings" dialog of this extension, I can't find a way to close it. It blocks the whole application and I have to terminate it. Besides, settings window is in black letters on dark background, very hard to read.

—
Reply to this email directly or view it on GitHub[github.com]https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_salt42_blueprint_issues_2&d=AAMCaQ&c=z0adcvxXWKG6LAMN6dVEqQ&r=SbTZMFe2IDI-qzAOWOcB4ikrkUV5u96hldynA-ZaiV8&m=swVH58llWNkzguKucilx-Pi-PlSBDVFir1yCc5LktHA&s=9DP6uBTlUSb4phlR9q1Cn0KYtoHLO8V94ApoSb5Bc-8&e=.

 NOTICE: This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by salt42** [comment]
brackets escape game^^ simple press esc ;)
sry for that.

**Comment by salt42** [comment]
@ jmo7 what is Awesome?

**Comment by jmo7** [comment]
> What is awesome?

That you’re responsive and quick to fix bugs  =)

Also, of course, Blueprint itself is really awesome!

Jeff Moyes

UX - Web Developer
jeffmoyes@familysearch.orgmailto:jeffmoyes@familysearch.org

On Oct 28, 2014, at 5:14 PM, salt42 <notifications@github.com<mailto:notifications@github.com>> wrote:

brackets escape game^^ simple press esc ;)
sry for that.

—
Reply to this email directly or view it on GitHub[github.com]https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_salt42_blueprint_issues_2-23issuecomment-2D60848320&d=AAMCaQ&c=z0adcvxXWKG6LAMN6dVEqQ&r=SbTZMFe2IDI-qzAOWOcB4ikrkUV5u96hldynA-ZaiV8&m=Z9BnU0leHfh4PsayMoeJnKmE8g9qbAOpSSXZhSOvvSA&s=tE_xd9kAiy9YygFpoUtwI9SiEVhR0egjX4VzL5KOS68&e=.

 NOTICE: This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by salt42** [comment]
nice thx!!
i'm also open for suggestions ;)

**Comment by antonbabkin** [comment]
Thanks :)
"Esc" is kind of obvious, but I forgot to try it. Still would be nice if
there was a small "x" button or something.

**Comment by salt42** [comment]
et voilà
its for you antonbabkin :)
