### ISSUE TITLE
Usage ?

### ISSUE THREAD

**Issue by SheepDomination** [salt42/blueprint#26]
How do I use this ?

**Comment by salt42** [comment]
sry for the late reaction! what exactly is your problem? after install you have a blue icon on the right side, just click on it.

**Comment by SheepDomination** [comment]
You don't mean 'outliner' ?

**Comment by salt42** [comment]
can you see the minimap? than on the top off the sidebar are 2 tabs, "outliner" and "minimap".
but usualy it's deadly simple.

**Comment by SheepDomination** [comment]
I see outliner and mini-map.  That's all :+1: ?

**Comment by salt42** [comment]
and on bottom is a config button ;)  i close here, if you have more question or suggestions  - feel free to ask.
