### ISSUE TITLE
php outline please!

### ISSUE THREAD

**Issue by wireinet** [salt42/blueprint#32]
HellO! Can you add ability to outline structure of php?

**Comment by salt42** [comment]
blueprint has allready the ability. maybe the content of the php file is the reason for the bug. can you test a real simple php file.

**Comment by wireinet** [comment]
![2017-01-14_16-24-41](https://cloud.githubusercontent.com/assets/23517333/21955203/fc31a0f2-da76-11e6-98ec-438703d531e6.jpg)
try to attach zip with php...and cant...
use php from word press. all of this is not support...

**Comment by salt42** [comment]
the outliner show only scopes like functions or classes.
and sry for the question, but why you open and close php so often in a .php file?

**Comment by wireinet** [comment]
hmmm...just normal work? approx. thank you...I thought it was wrong...it's not my business...I find this for example :)

**Comment by salt42** [comment]
i don't see the hole file but if there are no functions or classes in it, then that is the normal behavior.

**Comment by wireinet** [comment]
ok. just fine! close thread
Thank you for reply
