### ISSUE TITLE
[Feature Request] Ability to change font size in outline

### ISSUE THREAD

**Issue by jarquafelmu** [salt42/blueprint#35]
Hi Salt42. Thank you for this extension, it's the first outline extension for python that has successfully worked and grabbed all of the functions for me.

I was wondering if you would please expose the font size used in the outline in a settings file. I would like to shrink the font size as the text is a little large for me.

Thanks again for this extension.

**Comment by salt42** [comment]
sadly this project is near dead. :/ But the good thing is there is a config where you can set the font size. To open the config, there is a gear symbol in the bottom right corner.
