### ISSUE TITLE
Error generating outline with JS code

### ISSUE THREAD

**Issue by mattbrun** [salt42/blueprint#4]
Hi,
First of all thanks for you plugin :)

With the new versions of the plugin, it doesn't generate the outline of my JS code anymore.
Since I don't think I found the real source, I didn't make a pull request. Instead I posted some screenshot of my debugging procedure.

Anyway, When focusing on a JS file the outline was not generated.
Opening the Chrome debug console for Brackets I saw some errors on your outline.js file, so I added a console log just before the error line and this is the output (the error on the first line is of Theseus plugin):
![screenshot from 2014-11-07 16 03 23](https://cloud.githubusercontent.com/assets/1902043/4954862/bf220a46-6690-11e4-80f9-6a6151569a2d.png)
![screenshot from 2014-11-07 16 03 05](https://cloud.githubusercontent.com/assets/1902043/4954853/a77c4a46-6690-11e4-80d4-590c67dc9412.png)

So from here it seems that the `recursive(node)` function is called twice, once with the correct object you would expect, and once with a function.
Therefore I tried to add a check for the value of the `node` parameter at the beginning of the function in such a way: `if (typeof node !== 'object') return;`
![screenshot from 2014-11-07 16 07 58](https://cloud.githubusercontent.com/assets/1902043/4954908/234e1bfe-6691-11e4-96a2-8a3339b6973d.png)

At this point the outline generates correctly the module defined functions, but it also adds some `undefined` value which I guess derives from the second call of the function, when I return at the beginning
![screenshot from 2014-11-07 16 08 12](https://cloud.githubusercontent.com/assets/1902043/4954943/56dabcb6-6691-11e4-9219-b9f09cc50ede.png)

To try to resolve this I moved the check of the input after the variables initialization, and the output seems correct, even though there's still some spaceo on the left of the functions, which means it still consider the `undefined` parent
![screenshot from 2014-11-07 16 20 30](https://cloud.githubusercontent.com/assets/1902043/4955002/f73da5a6-6691-11e4-9723-2e9b46e335a7.png)
![screenshot from 2014-11-07 16 22 25](https://cloud.githubusercontent.com/assets/1902043/4955005/f97d2d78-6691-11e4-9e3f-f4602c7f2705.png)

**Comment by salt42** [comment]
can you post a piece of code to reproduce the error?

**Comment by mattbrun** [comment]
``` js
'use strict';

var config      = require('./config'),
    async       = require('async'),
    MongoClient = require('mongodb').MongoClient;

// clean "auths" collection
function cleanAuthsCollection (db) {
  // ...
}

function cleanCollections (db, collName, collOpsName) {
  // ...
}

function cleanDeletedData (db) {
  // ...
}

function cleanDB (db) {
  cleanAuthsCollection(db);
  cleanDeletedData(db);
}

function init () {
  // Since sharejs doesn't completely remove objects from the DB for delete ops
  // rewind possibility, we force the deletion of those objects
  MongoClient.connect(config.mongo.url + '?auto_reconnect', { safe: true }, function(err, db) {
    if(err) { throw err; }

    cleanDB(db);
    setInterval(async.apply(cleanDB, db), config.app.dbCleanInterval);
  });
}

module.exports.init = init;
```

**Comment by salt42** [comment]
i can't reproduce the bug with youre code.

**Comment by mattbrun** [comment]
Unfortunately for me the problem is still there...
I didn't managed to get deeper in my analysis of the problem, but at this point my guess is that there's some other extension who is interferring.
I hope I'll have more time to get deeper into this in the future, in the meanwhile thanks for your support :)
cheers

**Comment by mattbrun** [comment]
Btw, seems to be the same problem of #14

**Comment by salt42** [comment]
oh I did not think about other extension _shame_.
can you pls post your extensions?
and have you tried to activate the experimental js parser in the options?

**Comment by mattbrun** [comment]
I tried with the experimental parser, but still no outline.
These my extensions:
- BluePrint Beta
- Brackets Git
- Brackets Icons
- Code Folding
- Developer Tools in default browser
- Duplicate Files & Folders
- FuncDocr
- Intercative Linter
- Projects
- Quick MDN Doc
- Quick Search
- QuickDocsJS
- Stylus Extension for Brackets
- Theseus for Brackets
- Todo

**Comment by salt42** [comment]
i think i fixed it. we will see next update ;)
