### ISSUE TITLE
Sorting should be disabled for html

### ISSUE THREAD

**Issue by telis93** [salt42/blueprint#7]
I think sorting should be disabled for html.
I don't think it makes sense to sort the html tags.

In general I believe that there should be an option to disable sorting in every file.

**Comment by salt42** [comment]
thx for the void elements patch.

yes in the html tree, sorting makes no sense.
and sorting can be disabled in the options.

**Comment by telis93** [comment]
In options I see default sorting
which can be either none or asc.
But none doesn't appear to be working.

![brackets](https://cloud.githubusercontent.com/assets/3739293/4982570/b7fcbd94-6913-11e4-9e58-88ea42c34703.JPG)

The head appears to be sorted ok but not the body

**Comment by salt42** [comment]
found :)

**Comment by telis93** [comment]
found what?

**Comment by salt42** [comment]
the bug

**Comment by telis93** [comment]
Did you force push?

**Comment by salt42** [comment]
yesterday i did a force push

**Comment by telis93** [comment]
My commit is now gone :disappointed:

**Comment by salt42** [comment]
sry my bad!
but you can write a new one ;)

**Comment by telis93** [comment]
I am thinking of solving #8 :smile:
