### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by mlp73** [salt42/blueprint#9]
Couldn't install. Process stops, failure message.

**Comment by telis93** [comment]
What does the message say?

**Comment by mlp73** [comment]
Got only "Installation failed! An error occurred while starting the extension"

![skjermbilde 2014-11-13 kl 16 13 30](https://cloud.githubusercontent.com/assets/5936956/5030462/174f5502-6b50-11e4-8ae8-d23c90235181.png)

**Comment by telis93** [comment]
I can't reproduce that in windows. 
Which version of brackets are you using?

**Comment by mlp73** [comment]
Brackets sprint 0 build 1.0.0-15191 (release 3f2eb90a4) 
build timestamp: Fri Oct 31 2014 14:26:26 GMT-0700

**Comment by salt42** [comment]
can you install it manually and check if there are errors?

**Comment by mlp73** [comment]
I try by drag&drop of the .zip package but got unfortunately the same message. Was it what you meant by installing manually? (thx for help btw)

**Comment by salt42** [comment]
you can download blueprint over github and move the content in the extensions folder (in brackets in the help menu is a link to open the extensions folder)

**Comment by mlp73** [comment]
Ok. I did this way and in the list of extensions it now appears with "extension error". I can only delete it.

**Comment by salt42** [comment]
in brackets, you can press f12 (this open a debug window just like in the browser).
there you can search for a blueprint specific bug or make screens.
sry for the circumstances but I can't reproduce the bug.

**Comment by mlp73** [comment]
I'll do. No problem. I'm off for a couple of days now but I'll surely have a look and post back!

**Comment by burtnoir** [comment]
I had the same problem but got it working by making a small change in the preferences.js init function.  You need to move the first use of the PREFS object after the check.  As follows:

``` javascript
    exports.init = function () {
        $ui = $('<ul class="perf-list"></ul>');
        //@todo remove sometime
//      localStorage.removeItem("blueprintPrefs");
        localStorage.removeItem("blueprintPreferences");

        loadPrefs();

        //check first init before trying to use it
        if (PREFS === null) {
            PREFS = defaultPrefValues;
            savePrefs();
        } else {
            PREFS = $.extend({}, defaultPrefValues, PREFS);
            savePrefs();
        }

        //
        if (PREFS.generelopenOnStart === true) {
            PREFS.generelopenOnStart = 'right';
        }
    };

Hope that helps.
```

**Comment by salt42** [comment]
:+1:
and sry for that dirty code ;)

**Comment by mlp73** [comment]
Indeed, it was about that ;)
Thx for great help, and great plugin!
